on:
  push:
    branches:
      - main

name: Release

concurrency:
  group: semantic-release-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc
          cache-dependency-path: package-lock.json
      - name: Install deps
        run: npm install --ignore-scripts
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
